model:
  name: microsoft/deberta-v3-small
  dropout: 0.5
  freeze_backbone: false

train:
  learning_rate: 2e-5
  weight_decay: 0.01
  num_warmup_steps: 100
  num_training_steps: 1000
  grad_accum_steps: 4
  accelerator: cuda
  devices:
    - 0
  precision: 16-mixed
  val_check_interval: 1.0
  overfit_batches: 0
  num_sanity_val_steps: 4
  full_deterministic_mode: false
  benchmark: false
  gradient_clip_val: 1.0
  profiler:
  log_every_n_steps: 1
  batch_size_finder: false
  detect_anomaly: false
  matmul_precision: "medium"
  scaler_mode: "power"

data:
  csv_path: /mnt/d/sberML/SBT_ML_Ops_HW/second_hw/data/train.csv
  val_size: 0.2
  dataloader_num_wokers: 8
  batch_size: 8
  text_max_length: 512